/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SizingRouteImport } from './routes/sizing'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as AlignmentRouteImport } from './routes/alignment'
import { Route as IndexRouteImport } from './routes/index'

const SizingRoute = SizingRouteImport.update({
  id: '/sizing',
  path: '/sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignmentRoute = AlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/library': typeof LibraryRoute
  '/pipeline': typeof PipelineRoute
  '/sizing': typeof SizingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/library': typeof LibraryRoute
  '/pipeline': typeof PipelineRoute
  '/sizing': typeof SizingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/library': typeof LibraryRoute
  '/pipeline': typeof PipelineRoute
  '/sizing': typeof SizingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alignment' | '/library' | '/pipeline' | '/sizing'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alignment' | '/library' | '/pipeline' | '/sizing'
  id: '__root__' | '/' | '/alignment' | '/library' | '/pipeline' | '/sizing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignmentRoute: typeof AlignmentRoute
  LibraryRoute: typeof LibraryRoute
  PipelineRoute: typeof PipelineRoute
  SizingRoute: typeof SizingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sizing': {
      id: '/sizing'
      path: '/sizing'
      fullPath: '/sizing'
      preLoaderRoute: typeof SizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alignment': {
      id: '/alignment'
      path: '/alignment'
      fullPath: '/alignment'
      preLoaderRoute: typeof AlignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignmentRoute: AlignmentRoute,
  LibraryRoute: LibraryRoute,
  PipelineRoute: PipelineRoute,
  SizingRoute: SizingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
