/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TargetingRouteImport } from './routes/targeting'
import { Route as SizingRouteImport } from './routes/sizing'
import { Route as AlignmentRouteImport } from './routes/alignment'
import { Route as IndexRouteImport } from './routes/index'

const TargetingRoute = TargetingRouteImport.update({
  id: '/targeting',
  path: '/targeting',
  getParentRoute: () => rootRouteImport,
} as any)
const SizingRoute = SizingRouteImport.update({
  id: '/sizing',
  path: '/sizing',
  getParentRoute: () => rootRouteImport,
} as any)
const AlignmentRoute = AlignmentRouteImport.update({
  id: '/alignment',
  path: '/alignment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/sizing': typeof SizingRoute
  '/targeting': typeof TargetingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/sizing': typeof SizingRoute
  '/targeting': typeof TargetingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alignment': typeof AlignmentRoute
  '/sizing': typeof SizingRoute
  '/targeting': typeof TargetingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alignment' | '/sizing' | '/targeting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alignment' | '/sizing' | '/targeting'
  id: '__root__' | '/' | '/alignment' | '/sizing' | '/targeting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlignmentRoute: typeof AlignmentRoute
  SizingRoute: typeof SizingRoute
  TargetingRoute: typeof TargetingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/targeting': {
      id: '/targeting'
      path: '/targeting'
      fullPath: '/targeting'
      preLoaderRoute: typeof TargetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sizing': {
      id: '/sizing'
      path: '/sizing'
      fullPath: '/sizing'
      preLoaderRoute: typeof SizingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alignment': {
      id: '/alignment'
      path: '/alignment'
      fullPath: '/alignment'
      preLoaderRoute: typeof AlignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlignmentRoute: AlignmentRoute,
  SizingRoute: SizingRoute,
  TargetingRoute: TargetingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
